### ISSUE TITLE
[BE] Email Template For Forgot Passwords

### ISSUE THREAD

**Issue by xamppsul** [Betalogika/halokak-be-lumen#10]

**Comment by Oueael** [comment]
How about:

<html><body>


Forgot your password?
--
 
Hi [NAME}, follow the link below to reset your password. If you did not request to reset your password, you can ignore this email.
 
RESET YOUR PASSWORD | RESET YOUR PASSWORD
RESET YOUR PASSWORD
 


</body>
</html>Forgot your password?
Hi [NAME], follow the link below to reset your password. If you did not request to reset your password, you can ignore this email.
[RESET YOUR PASSWORD](link)

**Comment by xamppsul** [comment]
@suhafer monggo udah ready to testing lagi

**Comment by suhafer** [comment]
> How about:
> 
> ## Forgot your password?
>   Hi [NAME}, follow the link below to reset your password. If you did not request to reset your password, you can ignore this email.   RESET YOUR PASSWORD | RESET YOUR PASSWORD RESET YOUR PASSWORD  
> 
> Forgot your password? Hi [NAME], follow the link below to reset your password. If you did not request to reset your password, you can ignore this email. [RESET YOUR PASSWORD](link)

thanks for your suggestion @Oueael but we already implement email template based on our designer.
