### ISSUE TITLE
Saran perubahan format data db

### ISSUE THREAD

**Issue by suhafer** [Betalogika/halokak-be-lumen#3]
saran room dan chatroom
- user_id => mentor_user_id
- mentor => name dan photo 
- mentee_user_id
- mentee
- status => status room, integer or string =>contoh: “active”, “inactive”, “pending”
- users_id => user_id
- user => id dan name

saran kategori:
- nama => kebutuhan menampilkan judul kategorinya
- value => unique code category nya
- photo => foto kategori

Saran rekomendasi => by query dari table/collection mentor
- sort by createdAt
- sort by jumlah room yang terbuat dengan id dia

**Comment by xamppsul** [comment]
@suhafer terkait issue dari request kita, gw udah assigned to branch feat/mentorship terkait requestnya sisa gw pull req, untuk selanjutnya di review
