### ISSUE TITLE
Perbaikan pesan proses autentikasi

### ISSUE THREAD

**Issue by suhafer** [Betalogika/halokak-be-lumen#6]
1. Saat ini pesan yang dibalikkan dari api ketika sukses registrasi belum informatif bahwa butuh verifikasi

Ganti pesan ketika sukses registrasi menjadi seperti ini:
"Registrasi berhasil, silakan cek email untuk melanjutkan proses verifikasi"

2. Saat ini pesan yang dibalikkan dari api ketika gagal login karena belum verifikasi belum informatif

Ganti pesan ketika sukses registrasi menjadi seperti ini:
"Akun Anda belum diverifikasi, silakan cek email atau hubungi Admin"

**Comment by xamppsul** [comment]
@suhafer udah gw assigned ke branch yah, dan udah pull request jg
