### ISSUE TITLE
perbaikan logic deteksi validasi email atau username ketika login

### ISSUE THREAD

**Issue by suhafer** [Betalogika/halokak-be-lumen#8]
current:
- deteksi param "umail" lalu cek apakah ada simbol "@" untuk menentukan pengecekan melalui apa

Goals:
- ambil value param "umail" lalu pengecekan pertama berdasarkan email jikalau tidak ada lanjut ngecek username, jikalau tidak ada berarti invalid

**Comment by xamppsul** [comment]
@suhafer done kak suryo monggo udah ready to testing
